# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  basketdb:
    image: redis:alpine
    container_name: basketdb
    restart: always
    ports:
      - 6379:6379

  discountdb:
    image: postgres
    container_name: discountdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  orderdb:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: orderdb
    restart: always
    environment:
      - SA_PASSWORD=SwN12345678
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/root/.pgadmin

  catalog.api:
    container_name: catalog.api
    image: catalog.api
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    ports:
      - 8000:80
    environment:
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog:MinimumLevel:Default=Information
      - Serilog:MinimumLevel:Default:Override:Microsoft=Information
      - Serilog:MinimumLevel:Default:Override:System=Information
      - ElasticsearchConfiguration:Uri=http://elasticsearch:9200
    depends_on:
      - catalogdb
      - elasticsearch

  basket.api:
    container_name: basket.api
    image: basket.api
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile
    ports:
      - 8001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
      - "CacheSettings:ConnectionString=basketdb:6379"
      - EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672
      - Serilog:MinimumLevel:Default=Information
      - Serilog:MinimumLevel:Default:Override:Microsoft=Information
      - Serilog:MinimumLevel:Default:Override:System=Information
      - ElasticsearchConfiguration:Uri=http://elasticsearch:9200
    depends_on:
      - basketdb
      - rabbitmq
      - elasticsearch

  discount.api:
    container_name: discount.api
    image: discount.api
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.API/Dockerfile
    ports:
      - 8002:80
    environment:
      - "DatabaseSettings:connectionstring=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog:MinimumLevel:Default=Information
      - Serilog:MinimumLevel:Default:Override:Microsoft=Information
      - Serilog:MinimumLevel:Default:Override:System=Information
      - ElasticsearchConfiguration:Uri=http://elasticsearch:9200
    depends_on:
      - discountdb
      - elasticsearch

  discount.grpc:
    container_name: discount.grpc
    image: discount.grpc
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.Grpc/Dockerfile
    ports:
      - 8003:80
    environment:
      - "DatabaseSettings:connectionstring=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog:MinimumLevel:Default=Information
      - Serilog:MinimumLevel:Default:Override:Microsoft=Information
      - Serilog:MinimumLevel:Default:Override:System=Information
      - ElasticsearchConfiguration:Uri=http://elasticsearch:9200
    depends_on:
      - discountdb
      - elasticsearch

  ordering.api:
    container_name: ordering.api
    image: ordering.api
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile
    ports:
      - 8004:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678"
      - EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672
      - Serilog:MinimumLevel:Default=Information
      - Serilog:MinimumLevel:Default:Override:Microsoft=Information
      - Serilog:MinimumLevel:Default:Override:System=Information
      - ElasticsearchConfiguration:Uri=http://elasticsearch:9200
    depends_on:
      - orderdb
      - rabbitmq
      - elasticsearch

  ocelotapigw:
    container_name: ocelotapigw
    image: ocelotapigw
    build:
      context: .
      dockerfile: src/ApiGateways/OcelotApiGw/Dockerfile
    ports:
      - 8010:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog:MinimumLevel:Default=Information
      - Serilog:MinimumLevel:Default:Override:Microsoft=Information
      - Serilog:MinimumLevel:Default:Override:System=Information
      - ElasticsearchConfiguration:Uri=http://elasticsearch:9200
    depends_on:
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
      - elasticsearch

  shopping.aggregator:
    container_name: shopping.aggregator
    image: shopping.aggregator
    build:
      context: .
      dockerfile: src/ApiGateways/Shopping.Aggregator/Dockerfile
    ports:
      - 8005:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiSettings:CatalogUrl=http://catalog.api
      - ApiSettings:BasketUrl=http://basket.api
      - ApiSettings:OrderingUrl=http://ordering.api
      - Serilog:MinimumLevel:Default=Information
      - Serilog:MinimumLevel:Default:Override:Microsoft=Information
      - Serilog:MinimumLevel:Default:Override:System=Information
      - ElasticsearchConfiguration:Uri=http://elasticsearch:9200
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
      - elasticsearch

  aspnetrunbasics:
    container_name: aspnetrunbasics
    image: aspnetrunbasics
    build:
      context: .
      dockerfile: src/WebApps/AspnetRunBasics/Dockerfile
    ports:
      - 8006:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiSettings:GatewayUrl=http://ocelotapigw
      - Serilog:MinimumLevel:Default=Information
      - Serilog:MinimumLevel:Default:Override:Microsoft=Information
      - Serilog:MinimumLevel:Default:Override:System=Information
      - ElasticsearchConfiguration:Uri=http://elasticsearch:9200
    depends_on:
      - ocelotapigw
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
      - elasticsearch

  elasticsearch:
   container_name: elasticsearch
   image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
   ports:
    - 9200:9200
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   environment:
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node

  kibana:
   container_name: kibana
   image: docker.elastic.co/kibana/kibana:7.9.2
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:
  elasticsearch-data:
