# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  basketdb:
    image: redis:alpine
    container_name: basketdb
    restart: always
    ports:
      - 6379:6379

  discountdb:
    image: postgres
    container_name: discountdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/root/.pgadmin

  catalogapi:
    container_name: catalogapi
    image: catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    ports:
      - 8000:80
    environment:
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27018"
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - catalogdb
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  basketapi:
    container_name: basketapi
    image: basketapi
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile
    ports:
      - 8001:80
    environment:
      - "cachesettings:connectionstring=basketdb:6379"
      - aspnetcore_environment=development
    depends_on:
      - basketdb
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  discountapi:
    container_name: discountapi
    image: discountapi
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.API/Dockerfile
    ports:
      - 8002:80
    environment:
      - "DatabaseSettings:connectionstring=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
      - aspnetcore_environment=development
    depends_on:
      - basketdb
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:
