# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  basketdb:
    image: redis:alpine
    container_name: basketdb
    restart: always
    ports:
      - 6379:6379

  discountdb:
    image: postgres
    container_name: discountdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  orderdb:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: orderdb
    restart: always
    environment:
      - SA_PASSWORD=SwN12345678
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/root/.pgadmin

  catalog.api:
    container_name: catalog.api
    image: catalog.api
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    ports:
      - 8000:80
    environment:
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - catalogdb
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  basket.api:
    container_name: basket.api
    image: basket.api
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile
    ports:
      - 8001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
      - "CacheSettings:ConnectionString=basketdb:6379"
      - EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - basketdb
      - rabbitmq
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  discount.api:
    container_name: discount.api
    image: discount.api
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.API/Dockerfile
    ports:
      - 8002:80
    environment:
      - "DatabaseSettings:connectionstring=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - discountdb
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  discount.grpc:
    container_name: discount.grpc
    image: discount.grpc
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.Grpc/Dockerfile
    ports:
      - 8003:80
    environment:
      - "DatabaseSettings:connectionstring=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - discountdb
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  ordering.api:
    container_name: ordering.api
    image: ordering.api
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile
    ports:
      - 8004:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678"
      - EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - orderdb
      - rabbitmq
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  ocelotapigw:
    container_name: ocelotapigw
    image: ocelotapigw
    build:
      context: .
      dockerfile: src/ApiGateways/OcelotApiGw/Dockerfile
    ports:
      - 8010:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  shopping.aggregator:
    container_name: shopping.aggregator
    image: shopping.aggregator
    build:
      context: .
      dockerfile: src/ApiGateways/Shopping.Aggregator/Dockerfile
    ports:
      - 8005:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiSettings:CatalogUrl=http://catalog.api
      - ApiSettings:BasketUrl=http://basket.api
      - ApiSettings:OrderingUrl=http://ordering.api
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:
