# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mogno_data:/data/db

  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - catalogdb


volumes:
  mogno_data: